SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE

FROM MEMBER_PROFILE M

JOIN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) BR ON M.MEMBER_ID = BR.MEMBER_ID
JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID

ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;